# HTTP request test
# Work in Visual Studio Code with https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###
# Login
POST http://localhost:4000/login HTTP/1.1
content-type: application/json

{
	"username": "root",
	"password": "roO7p4s5wOrD"
}

###
# Get me
POST http://localhost:4000/ HTTP/1.1
content-type: application/json

{
	"query": "query Titres { titres( typeId: [apx, arc], domaineId: [m, h, s, g], statutId: [ins, val, ech], travauxId: [ins, enc, ach]) { id nom type { id nom } domaine { id nom } statut { id nom } travaux { id nom } substancesPrincipales { ...sub } substancesSecondaires { ...sub } } } fragment sub on Substance { id nom domaine type usage symbole alias gerep description legal { id nom description lien } }"
}

POST http://localhost:4000/login HTTP/1.1
