version: "3"

services:

  app:
    build: .
    depends_on: 
      - postgres
    environment:
      VIRTUAL_HOST: api.camino.pw
      VIRTUAL_PORT: ${NODE_PORT}
      LETSENCRYPT_HOST: api.camino.pw
      LETSENCRYPT_EMAIL: francoisromain@gmail.com
      PGHOST: postgres
    expose:
      - ${NODE_PORT}
  
  postgres: 
    image: postgres:alpine
    environment:
      PGUSER: ${PGUSER}
    expose:
      - ${PGPORT}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}

networks:
  default:
    external:
      name: nginx-proxy