type GeojsonMultiPolygon {
  type: FeatureType!
  geometry: GeometryMultiPolygon!
}

type GeometryMultiPolygon {
  type: GeometryTypeMultipolygon!
  coordinates: [[[[Float]]]]
}

type GeojsonPoints {
  type: FeatureCollectionType!
  features: [FeaturePoints]
}

type FeaturePoints {
  type: FeatureType!
  geometry: GeometryPoints!
}

type GeometryPoints {
  type: GeometryTypePoint!
  coordinates: [Float]
}

input InputGeojson {
  type: FeatureCollectionType!
  feature: [InputFeature]
}

input InputFeature {
  type: FeatureType!
  geometry: InputGeometry!
}

input InputGeometry {
  type: GeometryType
  coordinates: json
}

enum FeatureCollectionType {
  FeatureCollection
}

enum FeatureType {
  Feature
}

enum GeometryType {
  MultiPolygon
  Point
}

enum GeometryTypeMultipolygon {
  MultiPolygon
}

enum GeometryTypePoint {
  Point
}
