type Query {
  "Un titre"
  titre(id: String!): Titre
  "Liste de titres"
  titres(
    typeId: [TypeId]
    domaineId: [DomaineId]
    statutId: [StatutId]
    police: [Boolean]
  ): [Titre]

  substance(id: String!): Substance

  substances: [Substance]

  geojsonMultiPolygon(id: String!): GeojsonMultiPolygon

  geojsonMultiPolygons: [GeojsonMultiPolygon]

  geojsonPoints(id: String!): GeojsonPoints
}

type Mutation {
  titreAjouter(titre: InputTitre!): Titre

  titreModifier(titre: InputTitre!): Titre

  titreSupprimer(id: ID!): Titre
}

scalar json
