type Query {
  statuts: [Statut]

  "Un titre"
  titre(id: String!): Titre
  "Liste de titres"
  titres(
    typeIds: [TypeId]
    domaineIds: [DomaineId]
    statutIds: [StatutId]
    substances: [String]
  ): [Titre]

  substance(id: String!): Substance

  substances: [Substance]
}

type Mutation {
  titreAjouter(titre: InputTitre!): Titre

  titreModifier(titre: InputTitre!): Titre

  titreSupprimer(id: ID!): Titre
}

scalar json
