type Metas {
  types: [Type]
  domaines: [Domaine]
  statuts: [Statut]
}

type Type {
  id: TypeId!
  nom: String!
}

type Domaine {
  id: DomaineId!
  nom: String!
}

type Statut {
  id: StatutId!
  nom: String!
  couleur: Couleur!
}

type DemarcheType {
  id: ID!
  nom: String!
  dureeMax: Int!
  renouvelable: Boolean
  exception: Boolean
  ordre: Int
}

type DemarcheStatut {
  id: DemarcheStatutId!
  nom: String!
  couleur: Couleur!
}

type PhaseStatut {
  id: PhaseStatutId!
  nom: String!
  couleur: Couleur!
}

type EtapeType {
  id: ID!
  nom: String!
  acceptationAuto: Boolean
}

type EtapeStatut {
  id: EtapeStatutId!
  nom: String!
  couleur: Couleur!
}

type Emprise {
  id: EmpriseId!
  nom: String!
}

"""
- __apx__: Autorisation de prospections préalables (M, H, C)
- __arc__: Autorisation de recherches (C)
- __arg__: Autorisation de recherches (G)
- __axm__: Autorisation d'exploitation (M)
- __cxx__: Concession (M, H, G, S, C)
- __prh__: Permis exclusif de recherches (H)
- __prx__: Permis exclusif de recherches (M, G, S, C)
- __pxc__: Permis exclusif de carrières (C)
- __pxg__: Permis d'exploitation (G)
- __pxh__: Permis d'exploitation (H)
- __pxm__: Permis d'exploitation (M)
"""
enum TypeId {
  apx
  arc
  arg
  axm
  cxx
  prh
  prx
  pxc
  pxg
  pxh
  pxm
  pxx
}

"""
- __c__: Carrières
- __f__: Combustibles fossiles
- __g__: Géothermie
- __h__: Substances énergétiques
- __m__: Minéraux et métaux
- __r__: Eléments radioactifs
- __s__: Stockage
- __w__: Granulats marins
"""
enum DomaineId {
  c
  f
  g
  h
  m
  r
  s
  w
}

"""
- __dmc__: Demande classée
- __dmi__: Demande initiale
- __ech__: Échu
- __ind__: Indéterminé
- __mod__: Modification en instance
- __val__: Valide
"""
enum StatutId {
  dmc
  dmi
  ech
  ind
  mod
  val
}

"""
- __ter__: À terre
- __mer__: En mer
"""
enum EmpriseId {
  ter
  mer
}

"""
- __acc__: Acceptée
- __cls__: Classée sans suite
- __dep__: Déposée
- __eco__: En construction
- __ind__: Indeterminé
- __ini__: Initiée
- __ins__: En instruction
- __rej__: Rejetée
- __ret__: Retirée
- __ter__: Terminée
"""
enum DemarcheStatutId {
  acc
  cls
  dep
  eco
  ind
  ini
  ins
  rej
  ret
  ter
}

"""
- __val__: Valide
- __ech__: Échu
"""
enum PhaseStatutId {
  val
  ech
}

"""
- __acc__: Acceptation
- __def__: Défavorable
- __dre__: Défavorable avec réserves
- __fav__: Favorable
- __fre__: Favorable avec réserves
- __nul__: Non applicable
- __rej__: Rejet
- __nfa__: Non fait
- __fai__: Fait
"""
enum EtapeStatutId {
  acc
  def
  dre
  fav
  fre
  nul
  rej
  nfa
  fai
}

enum Couleur {
  error
  info
  neutral
  success
  warning
}

input InputType {
  id: TypeId!
}

input InputDomaine {
  id: DomaineId!
}

input InputDemarcheTypeId {
  id: ID!
}

input InputEtapeTypeId {
  id: ID!
}
