type Substance {
  id: ID!
  nom: String!
  domaine: Domaine
  type: String
  usage: String!
  symbole: String
  alias: [String]
  gerep: Int
  description: String
  legal: Legal!
}

type Legal {
  id: ID!
  nom: String!
  description: String!
  lien: String!
}

input InputSubstance {
  id: ID!
  nom: String!
  domaine: String!
  type: String
  usage: String!
  symbole: String
  alias: [String]
  gerep: Int
  description: String
  legal: InputLegal!
}

input InputLegal {
  id: ID!
  nom: String!
  description: String!
  lien: String!
}
