type Substance {
  id: ID!
  nom: String!
  domaine: Domaine
  type: String
  usage: String!
  symbole: String
  alias: [String]
  gerep: Int
  description: String
  legal: SubstanceLegal!
}

type SubstanceLegal {
  id: ID!
  nom: String!
  description: String!
  lien: String!
}

input InputSubstance {
  id: ID!
  nom: String!
  domaine: String!
  type: String
  usage: String!
  symbole: String
  alias: [String]
  gerep: Int
  description: String
  legal: InputSubstanceLegal!
}

input InputSubstanceLegal {
  id: ID!
  nom: String!
  description: String!
  lien: String!
}
