"Titre minier"
type Titre {
  """
  L'__id__ du titre est constituée de la concaténation:
  - du type en 3 lettres.
  - du nom du titre en minuscule, sans caractères spéciaux, avec des tirets au lieu des espaces.

  Exemples: _con-saint-elie_ ou _per-pedral_.
  """
  id: ID!
  nom: String!
  type: Type!
  domaine: Domaine!
  references: [Reference]
  statut: Statut!
  substances: [Substance]
  demarches: [Demarche]
}

type Reference {
  type: String
  nom: String!
}

type Etape {
  id: ID!
  type: EtapeType!
  statut: EtapeStatut!
  ordre: Int!
  date: String!
  duree: Int
  echeance: String
  surface: Float
  emprise: Emprise
  substances: [TitreSubstance]
  geojsonMultiPolygon: GeojsonMultiPolygon
  geojsonPoints: GeojsonPoints
  titulaires: [Entreprise]
  amodiataires: [Entreprise]
  utilisateurs: [Utilisateur]
}

type TitreSubstance {
  id: ID!
  nom: String!
  domaine: Domaine
  type: String
  symbole: String
  alias: [String]
  gerep: Int
  description: String
  legal: SubstanceLegal!
  connexe: Boolean
  ordre: Int
}

type Entreprise {
  id: ID!
  nom: String!
  service: String
  site: String
  email: String
  telephone: String
  adresse1: String
  adresse2: String
  codePostal: Int
  cedex: Int
  ville: String
}

type Utilisateur {
  id: ID!
  nom: String!
  prenom: String
  email: String
  telephoneMobile: String
  telephoneFixe: String
  administrationId: String
  entrepriseId: String
}

"tauuust"
input InputTitre {
  """
  L'__id__ du titre est constituée de la concaténation:
  - du type en 3 lettres.
  - du nom du titre en minuscule, sans caractères spéciaux, avec des tirets au lieu des espaces.

  Exemples: _con-saint-elie_ ou _per-pedral_.
  """
  id: ID!
  nom: String!
  type: InputType!
  domaine: InputDomaine!
  references: [InputReference]
}

input InputType {
  id: TypeId!
}

input InputDomaine {
  id: DomaineId!
}

input InputReference {
  type: String
}

input InputDemarche {
  titreId: String!
  id: ID!
  type: InputDemarcheTypeId!
  ordre: Int
}

input InputDemarcheTypeId {
  id: ID!
}

input InputEtape {
  id: ID!
  type: InputEtapeTypeId!
  duree: Int!
  date: String!
  surface: Float
  emprise: [InputEmpriseId]
  substances: [InputSubstanceId!]
}

input InputSubstanceId {
  id: ID!
}

input InputEtapeTypeId {
  id: ID!
}

input InputEmpriseId {
  id: EmpriseId!
}
