type Moi {
  id: ID!
  email: String!
  groupes: [Groupe]
  errors: [String!]
}

type Utilisateur {
  id: ID!
  email: String!
  password: String!
  nom: String
  prenom: String
  telephoneMobile: String
  telephoneFixe: String
  administrationId: String
  entrepriseId: String
  groupes: [Groupe]
}

type Groupe {
  id: ID!
  nom: String
}

type UtilisateurToken {
  token: String
  errors: [String!]
}

input InputUtilisateur {
  id: ID!
  email: String!
  password: String!
  nom: String
  prenom: String
  telephoneMobile: String
  telephoneFixe: String
  administrationId: String
  entrepriseId: String
}

input InputUtilisateurIdentifiants {
  id: ID!
  password: String!
}
