type Utilisateur {
  id: ID!
  email: String!
  nom: String
  prenom: String
  telephoneMobile: String
  telephoneFixe: String
  administrationId: String
  entrepriseId: String
  permissions: [Permission]
}

type UtilisateurToken {
  utilisateur: Utilisateur
  token: String
}

type Permission {
  id: ID!
  nom: String
}

input InputUtilisateur {
  id: ID!
  email: String!
  password: String!
  nom: String
  prenom: String
  telephoneMobile: String
  telephoneFixe: String
  administrationId: String
  entrepriseId: String
}
