require('dotenv').config()

const metas = require('./metas')
const repertoireAdministrations = require('./repertoire-administrations')
const repertoireEntreprises = require('./repertoire-entreprises')
const substances = require('./substances')
const titresC = require('./titres/c')
const titresG = require('./titres/g')
const titresH = require('./titres/h')
const titresM = require('./titres/m')
const titresM973 = require('./titres/m973')
const titresR = require('./titres/r')
const titresS = require('./titres/s')
const titresW = require('./titres/w')
const titresF = require('./titres/f')

const run = async () => {
  await metas()
  await repertoireAdministrations()
  await repertoireEntreprises()
  await substances()
  await titresC()
  await titresG()
  await titresH()
  await titresM()
  await titresM973()
  await titresR()
  await titresS()
  await titresW()
  await titresF()
}

run()
