const metas = require('./metas')
const repertoire = require('./repertoire')
const substances = require('./substances')
const titresA = require('./titres/a')
const titresC = require('./titres/c')
const titresG = require('./titres/g')
const titresH = require('./titres/h')
const titresM = require('./titres/m')
const titresM973 = require('./titres/m973')
const titresS = require('./titres/s')
const titresW = require('./titres/w')
const titresF = require('./titres/f')

const run = async () => {
  await metas()
  await repertoire()
  await substances()
  await titresA()
  await titresC()
  await titresG()
  await titresH()
  await titresM()
  await titresM973()
  await titresS()
  await titresW()
  await titresF()
}

run()
