name: Docs

on:
  release:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Generate docs
        run: |
          npm ci
          npm run docs
        env:
          CI: true
      - name: Build Docker image
        run: docker build -f Dockerfile.docs . --tag caminofr/camino-api-docs
      - name: Push Docker image to the Docker Hub
        run: |
          docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
          docker push caminofr/camino-api-docs
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
